apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-api
  
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      containers:
        - name: rag-api
          image: dhiraj918106/rag-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: rag-secret
                  key: OPENAI_API_KEY
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi